# Generated by Django 4.1.7 on 2023-03-29 22:52

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('product_logo', models.ImageField(upload_to='product_images/', validators=[product.models.validate_product_logo])),
                ('product_background', models.ImageField(upload_to='product_images/', validators=[product.models.validate_product_background])),
                ('product_foreground', models.ImageField(upload_to='product_images/', validators=[product.models.validate_product_foreground])),
                ('product_name', models.CharField(max_length=200)),
                ('product_title', models.CharField(max_length=20)),
                ('product_description', models.CharField(max_length=200)),
                ('product_short_description', models.CharField(max_length=100)),
                ('product_overview_title', models.CharField(max_length=200)),
                ('product_overview_description', models.TextField()),
                ('product_overview_image', models.ImageField(upload_to='product_images/', validators=[product.models.validate_product_overview_image])),
                ('product_feature_title', models.CharField(max_length=200)),
                ('product_feature_description', models.TextField()),
                ('product_feature_image', models.ImageField(upload_to='product_images/', validators=[product.models.validate_product_feature_image])),
                ('product_category', models.IntegerField()),
                ('product_logo_secondary', models.ImageField(upload_to='product_images/', validators=[product.models.validate_product_logo_secondary])),
            ],
        ),
    ]
