# Generated by Django 4.1.7 on 2023-03-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.ImageField(upload_to='service_images/')),
                ('service_title', models.CharField(max_length=200)),
                ('service_description', models.TextField()),
                ('service_foreground', models.ImageField(upload_to='service_images/')),
            ],
        ),
    ]
